#####To generate store info for a new city, state - copy a line and just edit the location value
python simple.py --term 'Indian Grocery' --location 'Ann Arbor, MI'
python simple.py --term 'Indian Grocery' --location 'Detroit, MI'
python simple.py --term 'Indian Grocery' --location 'San Fransisco, CA'
python simple.py --term 'Indian Grocery' --location 'New York City, NY'
python simple.py --term 'Indian Grocery' --location 'Jersey City, NJ'
python simple.py --term 'Indian Grocery' --location 'Edison, NJ'
python simple.py --term 'Indian Grocery' --location 'Rochester Hills, NY'
python simple.py --term 'Indian Grocery' --location 'Los Angeles, CA'
python simple.py --term 'Indian Grocery' --location 'Philadelphia, PA'
python simple.py --term 'Indian Grocery' --location 'Boston, MA'
